### PR TITLE
Move to gollum-lib

### PR DESCRIPTION
**Pull request by dometto**
Gollum-lib integration. This was a bit trickier than I expected, because the Gollum::Page class does not fit well into an MVC framework. There is no such thing as an unsaved Page in Gollum, and because of how grit works, a Page that is not yet committed to the repo has no name or filepath. I subclassed Gollum::Page and have attempted to mimic the typical Rails model behavior:

* a WikiPage can be instantiated if you pass a name, content, etc., supporting CRUD actions.
* when you call a CRUD action (e.g. save), the page will write itself to the repository and then '[populates](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/page.rb#L421)' itself with the newly created blob
  * Of course this opens new possibilities for all kinds of bugs, so I'd love to hear whether you guys think this design pattern is viable (cc @bartkamphorst @sunny @dancinglightning) 

  * To clearly distinguish between data that has been saved to the repo and data that has not been saved, a `WikiPage` has two methods: `#content` and `#new_content`. The former renders the page's data from the repo, the latter allows you to set new content for saving. So if you have a valid WikiPage:

    ```ruby
page.content # Reads and renders the page's blob data from the repo. Returns nil for unsaved pages.
page.new_content = "New content"
page.save # Save will not do anything if page.new_content is nil
page.content # Returns 'New content'
```
* Some other changes I've made:
  * No longer necessary to pass commit details for every CRUD action. Gollum-lib takes care of this under the hood. If the user wants to set these explicitly, they can set the Wiki's `default_committer_name` and `default_committer_email` attributes. I think authorization should be left optional, so that completely open wiki's are possible, as is gollum's default, or the user can implement his/her own authorization.
  * Removed dependencies on rugged etc.

Rendering is done by gollum-lib, so it's now possible to use all the goodies, like `[[_TOC_]]` and such. :)

### CODE REVIEW

**Comment by dancinglightning** [comment]
Well, some time has passed where i was hoping to hear some other voices. 

I would really encourage enspecially @sunny and @jamieoliver , ie people with commit rights, but also other gollum members to have a look at the request and say what they think, before i say something.

**Comment by dancinglightning** [comment]
Ok, just a small comment, We can discuss on the list.
This is a rewrite , not a pull request 
At a minimum it would need to be split into 4 pull request.
- formatting/small correction
- gollum-lib stuff
- authentication
- view handling

The last two need discussion and pre-approval.

If you want to make further pulls, please do it in a separate repository.
I need to close this because it breaks travis.

**Comment by dometto** [comment]
@dancinglightning, this PR is a rewrite because, unlike what we agreed upon, your project does not implement anything from the  gollum API (it does not even depend on any of the gollum gems). IMHO, it is at best misleading to users to host this repo in its current state under the gollum organisation. I was trying to show some good will and be constructive by opening this PR, but I do not get the feeling that you're really interested in working to turn this project into something not entirely unlike gollum. I can chop up the PR, of course, but it doesn't really seem like you would be willing to consider it even then. Please let me know if I'm completely mistaken about that, but otherwise I don't really see what the point of hosting this in this org is anymore.

**Comment by dancinglightning** [comment]
Well, if that's the way you want to play this go ahead.
Good setup with that pull "request"

I'm slightly tired of explaining that i didn't sign up for this.


Dawa Ometto wrote:

**Comment by dometto** [comment]
@dancinglightning: I take your reply, plus the fact that you just *deleted my code in the PR branch* by force-pushing to it (which is.. impolite), to indicate that you're not willing to take things in the direction we agreed upon from the outset. So I personally think it would be best for everyone if you continued your project somewhere else.

@sunny, @bartkamphorst, please let met know if you disagree. @dancinglightning, if you also agree, please fork or otherwise backup your code.

**Comment by dancinglightning** [comment]
@dometto Yes you can delete this repo, i really don't want to "cooperate" under these circumstances anymore.

I don't really know how you ever thought that "request" would go through. As you agree it was a rewrite (that broke travis). So how did you convince yourself you have the right to change another persons code to what you want.
It just shows no respect for the fact that i am the sole author and owner of the code.

If you would have just done what we agreed, i'd have accepted and we wouldn't have this mess.
So it was just to create this situation, as you don't really have any will to cooperate, you just want your way.

I participate in open source as a hobby, in my spare time, for fun. 
I don't want to be aggressed and bullied, so yes, it is better we part ways.

**Comment by dometto** [comment]
@dancinglightning, I'm sorry, I didn't realise you considered this project to be your exclusive domain. When you first contacted us we set some clear restrictions on this project, if it was to be part of this org, which you then completely ignored. So don't complain when people then try to hold you to that agreement.

When I mentioned that the project was taking a wrong turn from gollum's perspective (multiple times) you said you had no time to implement the project in the way we agreed, so I made the necessary changes myself. I could have done something else with my time, but I gave it a shot. I made it clear that this PR was not ready to merge and requested feedback, but you showed no signs of taking the needed changes seriously.

I might further mention that it is considered good form to give someone the chance to backup code before deleting it.

I will delete this repo in a couple of hours. Sorry things worked out this way, good luck with your project.

**Pull request closed without merging**
